vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
        attachments:
            uri_prefix: '%product_attachments%'
            upload_destination: '%kernel.project_dir%/public/%product_attachments%'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            inject_on_load: true
